### ISSUE TITLE
[EasyMonorepo] Unsupported symfony 5 having dependencies with version 4.2

### ISSUE THREAD

**Issue by AlbertLabarento** [eonx-com/easy-monorepo#177]
**Describe the bug**
Packages under 4.2 release can't be install to projects that supports symfony version 5

**To Reproduce**
Update symfony to version 5

**Expected behavior**
A [package-name] requires [dependency-package-name] version 4.2 to be installed, version 5 given

**Additional context**
N/A

**Comment by natepage** [comment]
Done in #181 , thank you.
