### ISSUE TITLE
[EasyStandard] Implement centralised standards configuration for EonX

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#184]
The idea behind this issue is for the `EasyStandard` package to have a way to generate the required files for a project to assert its code base against our company coding standards.

- console command?
- simply files to copy/paste?

Any ideas welcome!

**Comment by roman-eonx** [comment]
@natepage I think it will be enough to put our `rector.yaml` and `ecs.yaml` into the package, so everyone can copy-paste them (and disable some rules that can be specific to the project) or use right from the `vendor` dir.

**Comment by natepage** [comment]
@roman-eonx yes that's the idea

**Comment by natepage** [comment]
@roman-eonx @BOB41K1987 How are we going with this?

**Comment by roman-eonx** [comment]
We will continue working on this after EasyQuality is updated. The current idea is to introduce "sets", so every project can reuse them (and optionally disable some unwanted Rectors/Sniffs in the project's configs).

**Comment by ERuban** [comment]
Got it. Will implement it in a separate PR.

**Comment by natepage** [comment]
@roman-eonx @ERuban What's the status of this issue, can we consider it done now that EasyQuality there?

**Comment by ERuban** [comment]
@natepage I've already created sets in EasyQuality basing on PAY project (https://github.com/eonx-com/easy-quality/tree/main/config) but we need to discuss its content.

**Comment by natepage** [comment]
@ERuban @roman-eonx Thank you for that one! :muscle:
