### ISSUE TITLE
[EasyDecision] Symfony WebProfiler integration

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#187]
Create an integration for the Symfony WebProfiler to be able to see decision data in the profiler to make debugging easier.

**Comment by natepage** [comment]
What should we profile?

**Comment by albertlabarentojr** [comment]
Issue taken

**Comment by albertlabarentojr** [comment]
Hi @natepage  , I'm new to this web profiler integration, however, I found something interesting
https://symfony.com/doc/current/profiler.html#data-collectors

Maybe this can be a good start, just an idea

**Comment by natepage** [comment]
@albertlabarentojr Yes that's it 👍 

For examples about existing DataCollectors you can have a look at:

- https://github.com/eonx-com/easy-monorepo/blob/master/packages/EasySecurity/src/Bridge/Symfony/DataCollector/SecurityContextDataCollector.php
- https://github.com/eonx-com/easy-monorepo/blob/master/packages/EasyWebhook/src/Bridge/Symfony/DataCollector/WebhookDataCollector.php

The way to register them in the container:

- https://github.com/eonx-com/easy-monorepo/blob/master/packages/EasySecurity/src/Bridge/Symfony/Resources/config/services.php#L50
- https://github.com/eonx-com/easy-monorepo/blob/master/packages/EasyWebhook/src/Bridge/Symfony/Resources/config/debug.php#L21

And the associated twig templates (don't forget the icon 😉 ):

- https://github.com/eonx-com/easy-monorepo/blob/master/packages/EasySecurity/src/Bridge/Symfony/Resources/views/Collector/security_context_collector.html.twig
- https://github.com/eonx-com/easy-monorepo/blob/master/packages/EasyWebhook/src/Bridge/Symfony/Resources/views/Collector/webhook_collector.html.twig

**Comment by albertlabarentojr** [comment]
You literally gave me everything I need, thank you @natepage !

**Comment by natepage** [comment]
Done in #317
