### ISSUE TITLE
Remove any dependencies to eoneopay/eonx-com packages other than from monorepo

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#269]
This monorepo is the beginning of a "eonx framework", it allows us to centralised the development process for most of our reusable PHP packages. The objective is to get all the company's PHP packages here.

To do so, we should:

- Identify all dependencies to eoneopay/eonx-com package (not from monorepo)
- Identify if they are really needed
- If yes, what for?
- Then, how can we replace them? New package in monorepo? Feature in one of existing packages? Existing open-source package?

**Comment by natepage** [comment]
@roman-eonx @egor-dev @dextercampos @albertlabarentojr 

Can you guys check what `eoneopay/eonx-com` packages from outside of the monorepo are we still using in our projects, thank you.

**Comment by egor-dev** [comment]
@natepage only `eonx-com/apiformats` is used in Manage.

**Comment by natepage** [comment]
Done in 3.x branch.
