### ISSUE TITLE
Remove deprecated packages

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#271]
So far, this is the list of deprecated packages:

- EasyCfhighlander
- EasyDocker
- EasyIdentity

I think that with the work around moving the elasticsearch updates to logstash and so stop using the existing search package, we should be able to also deprecate:

- EasyEntityChange

We should remove those packages in v3

**Comment by natepage** [comment]
@roman-eonx @egor-dev @dextercampos @albertlabarentojr 

Can you guys confirm that none of your projects are using either `eonx-com/easy-identity` or `eonx-com/easy-entity-change`? Thank you!

I think we're really close from removing them! 💪

**Comment by egor-dev** [comment]
@natepage I confirm!

**Comment by natepage** [comment]
Done!
