### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#273]
This issue should be worked on LAST, once all the changes for v3 are made.

Once everything is done for v3 release, let's make sure the CI is green!

**Comment by roman-eonx** [comment]
@natepage maybe we should start fixing some issues right now (in `master`)? Just to make the current PRs easier to deal with.

**Comment by natepage** [comment]
@roman-eonx 100%

**Comment by natepage** [comment]
Done in #343
