### ISSUE TITLE
[EasyPagination] Doctrine ORM Paginator incorrect total items

### ISSUE THREAD

**Issue by jordancachero** [eonx-com/easy-monorepo#297]
**Describe the bug**
The query that counts total items does not remove duplicates (w/c doctrine does), if JOIN is used.
The query that counts total items becomes incorrect when Count is used with groupBy.

**To Reproduce**
On a repository that uses DoctrineOrmLengthAwarePaginator::setCriteria, add a join that will duplicate the row. Doctrine ORM hydrates and remove duplicates, but the counting does not.
Also add a groupBy clause and this will cause the counting to be incorrect.

**Expected behavior**
Total Items count should be correct.

**Comment by natepage** [comment]
@jordancachero Can you please provide an example of the code using the paginator with the issue. Would be helpful to understand what's going on, cheers.

**Comment by roman-eonx** [comment]
@jordancachero I've changed the issue title by adding the package name as a prefix. We usually do this to always see what package is affected by the issue. Btw, the same goes for pull requests in monorepo :wink:

**Comment by jordancachero** [comment]
Issue for when `Total Items Count > Actual Items`
- This is caused by Joins w/c creates duplicate rows

```
return $this->createLengthAwarePaginator($this->getEntityClass(), 'ga')
            ->setCriteria(static function (QueryBuilder $queryBuilder) use ($awardFilterData): void {
                     if ($awardFilterData->getNomineeId() !== null) {
                          $queryBuilder->innerJoin('ga.awardNominations', 'an')
                               ->andWhere('an.nominee = :nomineeId')
                               ->setParameter('nomineeId', $awardFilterData->getNomineeId())
                    }
....
```

Issue for when `Actual Items > Total Items Count`
- This is caused when group by is used. Ex scenario, is listing the Awards, sorted by nominations made count.

```
return $this->createLengthAwarePaginator($this->getEntityClass(), 'ga')
            ->setCriteria(static function (QueryBuilder $queryBuilder) use ($awardFilterData): void {
....
                       $queryBuilder
                            ->leftJoin('ga.awardNominations', 'an')
                            ->leftJoin('an.period', 'gap', Join::WITH, 'gap.currentPeriod = :currentPeriod')
                            ->setParameter('currentPeriod', true)
                            ->orderBy('COUNT(an.awardId)', $order)
                            ->groupBy('ga.awardId');
....
```

**Comment by natepage** [comment]
@jordancachero @roman-eonx 

Yes good point thank you, it is also used to generate the changelog automatically organised per package. The logic will require the PR title to be like `[<PackageName>] PR title`.

**Comment by natepage** [comment]
@jordancachero 

> Issue for when Total Items Count > Actual Items
> This is caused by Joins w/c creates duplicate rows

Please implement the snippet I gave you to default the fromAlias in the Doctrine trait.

>Issue for when Actual Items > Total Items Count
>This is caused when group by is used. Ex scenario, is listing the Awards, sorted by nominations made count.

Please use the `setGetItemsCriteria` method to set all criteria impacting the total items count.

**Comment by natepage** [comment]
@jordancachero I'm gonna close this issue as the code was merged 👍 

Thank you.
