### ISSUE TITLE
[EasyLock] Database Server gone doesn't throw exception

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#311]
**Describe the bug**
When having issues to communicate with the database, the lock logic behaves as it cannot acquire the lock but doesn't throw any exception. 

When used within a queue worker context, this has the side effect of keeping the worker alive but not processing any messages because couldn't acquire the lock.

**To Reproduce**
Use lock logic within a queue worker and break the database connection.

**Expected behavior**
There is no way for the worker to recover from this situation, so we should make sure that an exception is thrown and the worker killed.

**Comment by natepage** [comment]
Here the most common exception starting that bug:

```
PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /var/www/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:127
```

**Comment by natepage** [comment]
An experiment is in progress in estore project to ping the DBAL connection before each job to be processed, if ping isn't successful then kill the worker.

**Comment by ERuban** [comment]
Possible, this realisation can help https://github.com/facile-it/doctrine-mysql-come-back here.

**Comment by natepage** [comment]
@dextercampos what we've done in estore did the trick I believe? If yes we should start thinking about how to standardise it 😄

**Comment by dextercampos** [comment]
@natepage Yes and as discussed, we'll move this to EasyCore as 
- Messenger Middleware for Symfony - A trait similar to `EonX\EasyCore\Bridge\Symfony\Messenger\ProcessWithLockMiddleware`
- Listeners on Job Events for Laravel - An implementation using [Job Events](https://laravel.com/docs/8.x/queues#job-events)

---
This is the code snippet added in eStore before every job.

```
if ($entityManager->getConnection()->ping() === false) {
    $cache->forever('illuminate:queue:restart', Carbon::now()->getTimestamp());

    return;
}
```

The `ping` method is deprecated and as stated [here](https://github.com/doctrine/dbal/commit/e603a2e2333e043b9bba081dfaa2eda88814f478), `The wrapper connection will automatically handle the lost connection if the driver supports reporting it.`

So we need to use `$entityManager->getConnection()->getWrappedConnection` and catch `AssertionError` to simulate a `ping`.

**Comment by natepage** [comment]
@dextercampos sounds good, just some clarifications:

- What do you mean by `A trait similar to ...`, why a trait? We just need to create a middleware 😄 
- For the Wrapped connection, how are you planning to simulate? doing an sql query (e.g. `SELECT 1`) and catch the exception?

**Comment by dextercampos** [comment]
@natepage 
- My bad, yea it's a middleware not trait.
- Ah good question. I thought calling `getWrappedConnection` will throw `AssertionError` if no connection. But yea, I think we'll use same logic in the existing `ping` method and define our own method of ping? Basically copying this method. So we're safe when `ping` is removed in the next doctrine/dbal version. 

```
 $connection = $this->getWrappedConnection();

        if ($connection instanceof PingableConnection) {
            return $connection->ping();
        }

        try {
            $this->query($this->getDatabasePlatform()->getDummySelectSQL());

            return true;
        } catch (DBALException $e) {
            return false;
        }
```

**Comment by natepage** [comment]
@dextercampos with some logging around it I'm happy 😄

**Comment by natepage** [comment]
@dextercampos how are we going with that?

**Comment by natepage** [comment]
Done in #446
