### ISSUE TITLE
[EasyCore] TrimStrings middleware

### ISSUE THREAD

**Issue by egor-dev** [eonx-com/easy-monorepo#324]
We've found out that our Lumen projects do not trim the input string values from the API request (at least Manage and Points). We don't use PHP `trim` function manually either.

I'm thinking about replicating the [TrimStrings](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php) middleware from `illuminate/framework` package in our `easy-core` package in a bridge for Laravel. 

As for Symfony projects, we could implement something like a doctrine entity listener for that purpose as @natepage suggested.

**Comment by natepage** [comment]
@egor-dev Because all our projects are using doctrine I think that the listener could be a solution for everybody. Except if you have specific use cases that require the values to be trimmed before going to the db.

**Comment by egor-dev** [comment]
@natepage yeah, good point. I didn't think about that. I can't imagine a use case that requires the values to be trimmed before going to the DB for now.

**Comment by roman-eonx** [comment]
I can imagine a potential case when we need trimmed values before saving to the DB. For example, to calculate something (eg. full name from first and last names).
I'd prefer to transform the input at the beginning of the request processing. Unfortunately, it will require two different solutions for Lumen and Symfony-based projects. But they will be very simple, not a big problem.

@natepage what do you think?

**Comment by natepage** [comment]
@roman-eonx yes if there is a use case we should support it, I think it would require more than that but I think that we should think about "normal" symfony or make the trim class reusable so it can be implemented manually.

**Comment by natepage** [comment]
Done in #325
