### ISSUE TITLE
[EasyCore] Create Symfony messenger middleware to send messages to failure transport if async sender fails

### ISSUE THREAD

**Issue by albertlabarentojr** [eonx-com/easy-monorepo#329]
**Is your feature request related to a problem? Please describe.**
Failed async messages / job for instance transport dsn is not available, thus, it will fail sending this to async queue and should still be sent to failure transport.

**Describe the solution you'd like**
Will create a messenger middleware to handle the sending of the failed message to failure transport, that can be based on an existing issue posted on github (https://github.com/symfony/symfony/issues/35521)

**Comment by natepage** [comment]
@roman-eonx I would love to have your opinion on what to do when this happens? I'm reading through this issue after a long time and trying to think about what to do with it :smile:

**Comment by natepage** [comment]
Based on the activity on the related symfony issue, it looks like some solution will be provided moving forward, so I will close this issue and we will keep monitoring the activity in the Symfony project.
