### ISSUE TITLE
[EasyCore] Move reusable classes to the package

### ISSUE THREAD

**Issue by egor-dev** [eonx-com/easy-monorepo#342]
At the moment we have some repeated (and useful) classes in BMS and in EWMP projects. It's time to move them to EasyCore package along with their tests. Reason: to not duplicate their implementations and tests in projects again and again.

The list of classes (and suggested namespaces inside the package):
- `\App\Util\EntityManagerAwareTrait` -> `EonX\EasyCore\Bridge\Symfony\Trait\EntityManagerAwareTrait`
- `\App\Util\TranslatorAwareTrait` -> `EonX\EasyCore\Bridge\Symfony\Trait\TranslatorAwareTrait`
- `\App\Doctrine\EntityManagerResolver` -> `EonX\EasyCore\Bridge\Symfony\Doctrine\EntityManagerResolver`

**Comment by natepage** [comment]
@egor-dev should also add the DI code to automatically inject the entity manage and translator or it is already done by Symfony?

What's the purpose of `\App\Doctrine\EntityManagerResolver`?

**Comment by egor-dev** [comment]
@natepage we use `@required` annotation in the traits. So, yes, it's done by Symfony.
@roman-eonx could you please explain the purpose of `EntityManagerResolver`. I think you could do it fully and clearly :)

**Comment by roman-eonx** [comment]
`\App\Doctrine\EntityManagerResolver` allows us to inject EM directly instead of injecting `ManagerRegistry` (the recommended way of resolving the EM instance). It is a solution of a potential case where we want to re-open the closed EM instance and put it back to `ManagerRegistry`.

**Comment by roman-eonx** [comment]
All those traits are specific to Symfony only, as they rely on injection via setters. We've found this way very useful to not repeat the common dependencies injection in constructors all over the project code.

**Comment by natepage** [comment]
@egor-dev @roman-eonx any news on this one?

**Comment by egor-dev** [comment]
@natepage thanks for reminding. Assigned for @DKeeper. Will take care of that.

**Comment by natepage** [comment]
Done in #386
