### ISSUE TITLE
Research a way to log every HTTP request/response done in the apps

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#350]
The idea is to logs (no sure how/where yet) all the HTTP request/response triggered within our PHP applications to make debugging easier!

This feature should be able to be coupled with the Request/Correlation ID feature for even better results! ;)

**Comment by olamedia** [comment]
"[Apache Kafka](https://kafka.apache.org/uses#uses_website) is an open-source distributed event streaming platform used by thousands of companies for high-performance data pipelines, streaming analytics, data integration, and mission-critical applications." ?

**Comment by albertlabarentojr** [comment]
As a starting point, we may look at how we implement "Interceptors"
**List of Interceptors**
- AddRequestHeader
- AddResponseHeader
- ConditionalInterceptor
- DecompressResponse
- FollowRedirects
- ForbidUriUserInfo
- IfOrigin
- ModifyRequest
- ModifyResponse
- RemoveRequestHeader
- RemoveResponseHeader
- RetryRequests
- SetRequestHeader
- SetRequestHeaderIfUnset
- SetResponseHeader
- SetResponseHeaderIfUnset
- CookieHandler
- PrivateCache

which can work regardless of which HttpClient (guzzle, symfony httpclient, etc)

**Comment by natepage** [comment]
@albertlabarentojr Or I think we could just have a look at using the `getInfo()` method on the response given by the Symfony HttpClient 😄

**Comment by natepage** [comment]
Simple solution has been implemented already, see [WithLoggingHttpClient](https://github.com/eonx-com/easy-monorepo/blob/master/packages/EasyCore/src/HttpClient/Symfony/WithLoggingHttpClient.php).

If something more is needed let's open a more specific issue.
