### ISSUE TITLE
[EasyCore] TrimStrings in Symfony decorates non-existent service

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#352]
**Describe the bug**
The service "EonX\EasyCore\Bridge\Symfony\Serializer\TrimStringsNormalizer" has a dependency on a non-existent service "api_platform.jsonapi.normalizer.item".

**To Reproduce**
Upgrade `eonx-com/easy-core` to latest in Symfony Project

**Comment by natepage** [comment]
@egor-dev @roman-eonx

**Comment by egor-dev** [comment]
Refactored.
