### ISSUE TITLE
[EasyCore] Make JsonbType type name value uppercase

### ISSUE THREAD

**Issue by egor-dev** [eonx-com/easy-monorepo#360]
Update `EonX\EasyCore\Doctrine\DBAL\Types\JsonbType::TYPE_NAME` value to be uppercase. It will make our migrations consistent (see screenshot).

![image](https://user-images.githubusercontent.com/13471770/93766321-6d4b9d80-fc40-11ea-884a-486eda8d203d.png)

**Comment by natepage** [comment]
Done in #361
