### ISSUE TITLE
[EasyErrorHandler] Error Message Translation Issue

### ISSUE THREAD

**Issue by buddyshontogan** [eonx-com/easy-monorepo#391]
**Describe the bug**
The bug is about the translation of error messages from a Symfony application making use of the package due to having different configurations used for its `translation_domain`. The package uses `EasyErrorHandlerBundle` as its `translation_domain` as Symfony makes use of `messages`. Overriding the `translation_domain` configuration of either the package or the application will cause one of them to have its error message not be translated.

**To Reproduce**
1.  Install the package
2. Extend one of the Abstract Classes provided by the package to your Exceptions
3. Run a Test Case which will throw the Exception having the custom message from the application
4. Run another Test Case which will throw the Exception using the message generated by the package
4. The response should show if the message generated by the package or the application is translated

**Expected behavior**
The error messages should be translated for both the package and the application with different `translation_domain` configurations.

**Comment by natepage** [comment]
Done in #392
