### ISSUE TITLE
Unexpected Rector result for RemoveUnusedPrivatePropertyRector

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#398]
![Screen Shot 2020-10-19 at 11 20 38 pm](https://user-images.githubusercontent.com/11576446/96450420-e8b16680-1261-11eb-806f-cbdfd6718302.png)

@TomasVotruba I've just ran Rector on the monorepo, and this is what I got.. It breaks the code because it doesn't set the time on the `$data` array, any idea why?

**Comment by natepage** [comment]
It also did that in `packages/EasyErrorHandler/src/Builders/ExtendedExceptionBuilder.php` for the `$exceptionKey` property

**Comment by TomasVotruba** [comment]
I'll look on it, thanks for reporting

**Comment by natepage** [comment]
@TomasVotruba not sure what's happening, maybe it's related to my local dependencies because I've just pushed and rector is happy... lol

https://github.com/eonx-com/easy-monorepo/runs/1275160468?check_suite_focus=true

**Comment by natepage** [comment]
@TomasVotruba ok I confirm it was my local dependencies, I've removed them, removed my `composer.lock` file, installed again and rector is happy..

**Comment by TomasVotruba** [comment]
:+1: Glad I could help :smile:
