### ISSUE TITLE
[EasyErrorHandler] Can we bind ErrorHandler class in ErrorHandlerInterface for Laravel/Lumen setup

### ISSUE THREAD

**Issue by jayaregalinadaflexisourceit** [eonx-com/easy-monorepo#429]
**Is your feature request related to a problem? Please describe.**
Based on the documentation, you can inject `ErrorHandlerInterface` as dependency into your application. However, this contract is not bind to any thing at all, in Laravel/Lumen setup but in Symfony setup, it does.

**Describe the solution you'd like**
If we can bind the `ErrorHandler` used in `ExceptionHandler`.

**Describe alternatives you've considered**
I'm not sure any alternatives on this since the `ExceptionHandler` follows the illuminates' exception handler.

**Additional context**
Here is the example binding of `ExceptionHandler` in Laravel/Lumen setup, between the line `38-48`
```php
// EasyErrorHandlerServiceProvider.php
public function register(): void 
{
...
       $this->app->singleton(
            IlluminateExceptionHandlerInterface::class,
            function (): IlluminateExceptionHandlerInterface {
                return new ExceptionHandler(new ErrorHandler(
                    $this->app->make(ErrorResponseFactoryInterface::class),
                    $this->app->tagged(BridgeConstantsInterface::TAG_ERROR_RESPONSE_BUILDER_PROVIDER),
                    $this->app->tagged(BridgeConstantsInterface::TAG_ERROR_REPORTER_PROVIDER),
                    (bool)\config('easy-error-handler.use_extended_response', false)
                ), $this->app->make(TranslatorInterface::class));
            }
        );
...
}
```

**Comment by natepage** [comment]
Done in #438
