### ISSUE TITLE
[EasyErrorHandler] Incorrect translation for Laravel/Lumen setup

### ISSUE THREAD

**Issue by jayaregalinadaflexisourceit** [eonx-com/easy-monorepo#431]
**Describe the bug**
All exceptions' default user message are unable to read because translations are not properly setup.

**To Reproduce**
Extend any exceptions from this package in Laravel/Lumen setup and try to throw any of that error into your application.

```php
// app\Exceptions\UnprocessableEntityException.php
final class UnprocessableEntityException extends ErrorException
{
    protected $statusCode = Response::HTTP_UNPROCESSABLE_ENTITY; // 422
}
```

Throw this exception in to your application

```php
...
throw new UnprocessableEntityException();
...
```

**Expected behavior**
All exceptions have their own default `$userMessage` property, depending on which exception. In the example above, a response should look like:

```
// STATUS: 422 Unprocessable Entity
{
  "code": 0,
  "message": "Oops, something went wrong.", // `exceptions.default_user_message`
  "sub_code": 0,
  "time": "2020-12-05T03:49:16Z"
}
```

**Additional context**
I think because of the `UserMessageBuilder` (from default builder) are only translating the user message without namespace. A couple of workarounds can be done here, like creating another UserMessageBuilder into your app or copying the `messages.php`  into your existing `resources/lang/{locale}/exceptions.php` translation.

**Comment by natepage** [comment]
Done in #447
