### ISSUE TITLE
[EasyBankFiles] DE file parser assumes DE file format (not DE Return file)

### ISSUE THREAD

**Issue by nick-lc** [eonx-com/easy-monorepo#652]
The line below assumes that column 113 of a DE file transaction is for the withholding tax:
https://github.com/eonx-com/easy-monorepo/blob/19c69e230dd776165abed27b190b439046f1f10a/packages/EasyBankFiles/src/Parsers/DirectEntry/Parser.php#L212

This is as documented by [NAB](https://www.nab.com.au/content/dam/nabconnectcontent/file-formats/nab-connect-consolidated-file-format-specification_v0.05-pdf.pdf):
![image](https://user-images.githubusercontent.com/44986892/125231283-d27e9580-e31d-11eb-88bd-09c58152cc94.png)

But for DE Return files, column 113 is actually for original day of processing from the corresponding DE file:
![image](https://user-images.githubusercontent.com/44986892/125231342-efb36400-e31d-11eb-927a-32e9d2e6b7a8.png)

I don't think we actually use this field but I noticed the issue while investigating an issue with the naming of DE Return file records (https://eonx.atlassian.net/browse/PLU-3538).

**Comment by natepage** [comment]
@nick-lc thank you for that, I think the best approach here would be to create a separate parser for DE Return files.

**Comment by nick-lc** [comment]
I don't think we actually need to parse DE files.

We create DE files ourselves (using the ABA generator) and we receive DE Return files. So we really only need to parse DE Return files.

It might be a case of just fixing up the field as described above. (And maybe renaming the parser to make it clearer that it's for return files, if you're willing!)

**Comment by natepage** [comment]
@nick-lc in order not to introduce a BC break, I will create a new Parser, in case someone else is using the existing Parser for valid reasons.
Are we sure this is the only difference between the 2 files?

**Comment by natepage** [comment]
Done in #668
