### ISSUE TITLE
[EasyDecision] Throwing ContextNotSetException if dependency uses decision as well

### ISSUE THREAD

**Issue by jayaregalinadaflexisourceit** [eonx-com/easy-monorepo#721]
**Describe the bug**

When a dependency also uses Decision and will later inject in a different class/service, a `ContextNotSetException` will throw, stated that `You cannot called getContext() before decision has been made`

**To Reproduce**
- Create a class/service (ServiceA) that uses decision
- Then, inject that class/service to another class/service (ServiceB) that also uses decision
- Invoke or run the newly created class/service (ServiceB)
- I created a [gist](https://gist.github.com/jayaregalinadaflexisourceit/c9baac1283db8886f8c37b27f661c2d0) for this 

**Expected behavior**

The `ContextNotSetException` should not throw at all, but I'm not sure why the `DecisionDataCollector` is already getting the context.

**Additional context**

- To fixed the data collector in profiler, I just renamed the template (in line 37 at `easy-decision/src/Bridge/Symfony/Resources/config/services.php`) to `@EasyDecisionSymfony/Collector/decision_collector.html.twig`

**Comment by natepage** [comment]
@jayaregalinadaflexisourceit Thank you very much for this issue, it looks like the data collector was trying to get the context of all decisions instantiated, regardless if they've been made or not, I've released a fix in `3.3.11` please let me know if it fixes your issue.

**Comment by natepage** [comment]
Was fixed in https://github.com/eonx-com/easy-monorepo/releases/tag/3.3.11, feel free to re-open if the issue persisted.
