### ISSUE TITLE
[EasyErrorHandler]/[EasyBugSnag] -  Exceptions having a parent exception of HandlerException not being ignored from config

### ISSUE THREAD

**Issue by buddyshontogan** [eonx-com/easy-monorepo#801]
**Describe the bug**
Any exceptions having its parent exception of `Symfony\Component\Messenger\Exception\HandlerFailedException` is still being picked up by bugsnag even though we have set it to be ignored from the config. 

**To Reproduce**
- Create a `message` having its `handler` to throw an exception (eg. ValidationException).
- Add the exception under `bugsnag_ignored_exceptions` in the `easy_error_handler` config.
- Dispatch the `message` expecting the exception from the `handler` to be thrown
- Bugsnag will still pick up the exception from the handler because the parent exception thrown is `Symfony\Component\Messenger\Exception\HandlerFailedException` even if it is to be ignored by bugsnag.
**Expected behavior**
- Once an exception is added under `bugsnag_ignored_exceptions` in the `easy_error_handler` config, it should be ignored by bugsnag.

**Additional context**
- The package should be able to understand that if an exception has a parent exception of `Symfony\Component\Messenger\Exception\HandlerFailedException`, it needs to look for any child exceptions of the said parent exception. Once the package has determined the child exceptions, it should be able to base its logic of ignoring it from bugsnag considering that the child exception is added under the `bugsnag_ignored_exceptions` from the `easy_error_handler` config.

**Comment by natepage** [comment]
Done in #803
