### ISSUE TITLE
[EasySecurity] Invalid response for Unauthorized error

### ISSUE THREAD

**Issue by mvlad** [eonx-com/easy-monorepo#831]
**Describe the bug**

`EasyErrorHandler` allows defining field names for an HTTP response via [config](https://github.com/eonx-com/easy-error-handler/blob/master/src/Bridge/Symfony/DependencyInjection/Configuration.php#L62). We use the following config:
```
return static function (ContainerConfigurator $containerConfigurator): void {
    $containerConfigurator->extension('easy_error_handler', [
        'response' => ['sub_code' => 'subCode'],
    ]);
};
```

But `EasySecurity` [ignores](https://github.com/eonx-com/easy-security/blob/master/src/Bridge/Symfony/Factories/AuthenticationFailureResponseFactory.php#L39) `EasyErrorHandler`'s config for `Unauthorized` request:
```
{
  "message": "Unauthorized",
  "code": 401,
  "sub_code": 0
}
```

**Expected behavior**
The response should be 
```
{
  "message": "Unauthorized",
  "code": 401,
  "subCode": 0
}
```

**Comment by natepage** [comment]
@mvlad Good point, and that's because we are trying not to create to many dependencies between packages as people who wants to use `eonx-com/easy-security` don't necessarily want to use `eonx-com/easy-error-handler` and we shouldn't force them to do so.
As an easy solution, would you mind create a PR so change easy-security response, thank you

**Comment by roman-eonx** [comment]
@natepage what is your proposal? Just to change `sub_code` to `subCode`? Or add a config for this?

BTW, do we still use sub-codes anywhere in our projects? And if we do use them, do all our projects use camelCase in API responses?

**Comment by natepage** [comment]
@roman-eonx simply change it to camelcase, no config for this. All our projects are using easy-error-handler so yes returning subCodes, are they really used? No I don't think so but we should start using them lol
And yes camelCase.
